name: My First WorkFlow

# trigger
on:
- push

# Jobs in the workflow
jobs:
| my-first-workflow:
# OS that this job will be running on
runs-on: ubuntu-lastest

# list of steps to perform task
steps:
- name echo the date
  run: echo "The current time and date in Github is $(date)"